In [1]:
import pandas as pd
from keras.datasets import boston_housing

(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()
print(boston_housing.load_data.__doc__)

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/boston_housing.npz
57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Loads the Boston Housing dataset.

    This is a dataset taken from the StatLib library which is maintained at
    Carnegie Mellon University.

    **WARNING:** This dataset has an ethical problem: the authors of this
    dataset included a variable, "B", that may appear to assume that racial
    self-segregation influences house prices. As such, we strongly discourage
    the use of this dataset, unless in the context of illustrating ethical
    issues in data science and machine learning.

    Samples contain 13 attributes of houses at different locations around the
    Boston suburbs in the late 1970s. Targets are the median values of
    the houses at a location (in k$).

    The attributes themselves are defined in the
    [StatLib website](http://lib.stat.cmu.edu/datasets/boston).

    Args:
        path: path where to cache the dataset locally
            (relative to `~/.keras/datasets`).
        test_split: fraction of the data to reserve as test set.
        seed: Random seed for shuffling the data
            before computing the test split.

    Returns:
        Tuple of NumPy arrays: `(x_train, y_train), (x_test, y_test)`.

    **x_train, x_test**: NumPy arrays with shape `(num_samples, 13)`
        containing either the training samples (for x_train),
        or test samples (for y_train).

    **y_train, y_test**: NumPy arrays of shape `(num_samples,)` containing the
        target scalars. The targets are float scalars typically between 10 and
        50 that represent the home prices in k$.

In [20]:
train_df = pd.DataFrame(
    train_data,
    columns = [f"Feature{n}" for n in range(1,14)]
)
train_df.loc[:,"Label"] = train_targets
train_df.describe()

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,Feature11,Feature12,Feature13,Label
count,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000
mean,3.745111,11.480198,11.104431,0.061881,0.557356,6.267082,69.010644,3.740271,9.440594,405.898515,18.475990,354.783168,12.740817,22.395050
std,9.240734,23.767711,6.811308,0.241238,0.117293,0.709788,27.940665,2.030215,8.698360,166.374543,2.200382,94.111148,7.254545,9.210442
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,188.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081437,0.000000,5.130000,0.000000,0.453000,5.874750,45.475000,2.077100,4.000000,279.000000,17.225000,374.672500,6.890000,16.675000
50%,0.268880,0.000000,9.690000,0.000000,0.538000,6.198500,78.500000,3.142300,5.000000,330.000000,19.100000,391.250000,11.395000,20.750000
75%,3.674808,12.500000,18.100000,0.000000,0.631000,6.609000,94.100000,5.118000,24.000000,666.000000,20.200000,396.157500,17.092500,24.800000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.725000,100.000000,10.710300,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [21]:
def standardize_and_scale(df):
  df = df.copy()
  #scale all columns to be 1-2 digit numbers
  df["Feature4"] = df["Feature4"] * 10
  df["Feature5"] = df["Feature5"] * 100
  df["Feature6"] = df["Feature6"] * 10
  df["Feature10"] = df["Feature10"] / 10
  df["Feature12"] = df["Feature12"] / 5
  return df

standardize_and_scale(train_df).describe()

,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,Feature9,Feature10,Feature11,Feature12,Feature13,Label
count,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000,404.000000
mean,3.745111,11.480198,11.104431,0.618812,55.735594,62.670817,69.010644,3.740271,9.440594,40.589851,18.475990,70.956634,12.740817,22.395050
std,9.240734,23.767711,6.811308,2.412384,11.729310,7.097876,27.940665,2.030215,8.698360,16.637454,2.200382,18.822230,7.254545,9.210442
min,0.006320,0.000000,0.460000,0.000000,38.500000,35.610000,2.900000,1.129600,1.000000,18.800000,12.600000,0.064000,1.730000,5.000000
25%,0.081437,0.000000,5.130000,0.000000,45.300000,58.747500,45.475000,2.077100,4.000000,27.900000,17.225000,74.934500,6.890000,16.675000
50%,0.268880,0.000000,9.690000,0.000000,53.800000,61.985000,78.500000,3.142300,5.000000,33.000000,19.100000,78.250000,11.395000,20.750000
75%,3.674808,12.500000,18.100000,0.000000,63.100000,66.090000,94.100000,5.118000,24.000000,66.600000,20.200000,79.231500,17.092500,24.800000
max,88.976200,100.000000,27.740000,10.000000,87.100000,87.250000,100.000000,10.710300,24.000000,71.100000,22.000000,79.380000,37.970000,50.000000